# Generated by Django 2.2.5 on 2020-01-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sold', models.IntegerField()),
                ('price_sold', models.FloatField()),
                ('date_sold', models.DateField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_simulator_app.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_bought', models.IntegerField()),
                ('price_bought', models.FloatField()),
                ('date_bought', models.DateField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_simulator_app.Stock')),
            ],
        ),
    ]
